### ISSUE TITLE
0.1.0 checklist

### ISSUE THREAD

**Issue by sofish** [sofish/donuts#1]
- [ ] app layout
- [ ] default UI
- [x] proxy config
- [ ] platform support ( auto detect? )
- [ ] document: getting start ( link with Onsen UI )
- [ ] document: join
- [ ] demo app: hackers news
